- job:
    name: devstack-plugin-ceph-tempest-base
    parent: tempest-full
    description: |
      Base integration tests that runs with the ceph devstack plugin.
      Former names for this job where:
        * legacy-tempest-dsvm-full-devstack-plugin-ceph
        * gate-tempest-dsvm-full-devstack-plugin-ceph-ubuntu-xenial
      The original job included support for an un-used tempest-conf.sh:
        # If an in-repo configuration exists, source it.  This will likely
        # override DEVSTACK_GATE_TEMPEST_REGEX to further refine the set of
        # tests being run.
    required-projects:
      - openstack/cinder-tempest-plugin
      - openstack/devstack-plugin-ceph
    timeout: 7200
    vars:
      devstack_plugins:
        devstack-plugin-ceph: https://opendev.org/openstack/devstack-plugin-ceph
      devstack_localrc:
        ENABLE_FILE_INJECTION: false
        TEMPEST_PLUGINS: '/opt/stack/cinder-tempest-plugin'
        ENABLE_VOLUME_MULTIATTACH: false
        TEMPEST_RUN_VALIDATION: false
      tox_envlist: all
      tempest_test_regex: |
              (^tempest\.(api|scenario\.test_encrypted_cinder_volumes|scenario\.test_volume|scenario\.test_shelve_instance)|(^cinder_tempest_plugin))
      tempest_test_blacklist: '{{ ansible_user_dir }}/{{ zuul.projects["opendev.org/openstack/devstack-plugin-ceph"].src_dir }}/tempest_blacklist.txt'

- job:
    name: devstack-plugin-ceph-tempest
    parent: devstack-plugin-ceph-tempest-base
    description: |
      Integration tests that runs with the ceph devstack plugin and py27.
    branches:
      - stable/ocata
      - stable/pike
      - stable/queens
      - stable/rocky

- job:
    name: devstack-plugin-ceph-tempest
    parent: devstack-plugin-ceph-tempest-base
    description: |
      Integration tests that runs with the ceph devstack plugin and py27.

      This job enable the multiattach feature enable from stein on.

    # This job runs with multiattach enable from stable/stein on.
    branches:
      - stable/stein
      - stable/train
    vars:
      devstack_localrc:
        ENABLE_VOLUME_MULTIATTACH: true

- job:
    name: devstack-plugin-ceph-tempest-py3-base
    parent: tempest-full-py3
    description: |
      Base integration tests that runs with the ceph devstack plugin and py3.
      Former names for this job where:
        * legacy-tempest-dsvm-py35-full-devstack-plugin-ceph
        * gate-tempest-dsvm-py35-full-devstack-plugin-ceph-ubuntu-xenial-nv
      The original job included support for an un-used tempest-dsvm-ceph-rc
      hosted at /opt/stack/new/nova/devstack/tempest-dsvm-ceph-rc.
    required-projects:
      - openstack/cinder-tempest-plugin
      - openstack/devstack-plugin-ceph
    timeout: 7200
    vars:
      devstack_localrc:
        ENABLE_FILE_INJECTION: false
        TEMPEST_PLUGINS: '/opt/stack/cinder-tempest-plugin'
        ENABLE_VOLUME_MULTIATTACH: false
        TEMPEST_RUN_VALIDATION: false
      devstack_plugins:
        devstack-plugin-ceph: https://opendev.org/openstack/devstack-plugin-ceph
      tox_envlist: all
      tempest_test_regex: |
              (^tempest\.(api|scenario\.test_encrypted_cinder_volumes|scenario\.test_volume|scenario\.test_shelve_instance)|(^cinder_tempest_plugin))
      tempest_test_blacklist: '{{ ansible_user_dir }}/{{ zuul.projects["opendev.org/openstack/devstack-plugin-ceph"].src_dir }}/tempest_blacklist.txt'

- job:
    name: devstack-plugin-ceph-tempest-py3
    parent: devstack-plugin-ceph-tempest-py3-base
    description: |
      Integration tests that runs with the ceph devstack plugin and py3.
    branches:
      - stable/ocata
      - stable/pike
      - stable/queens
      - stable/rocky

- job:
    name: devstack-plugin-ceph-tempest-py3
    parent: devstack-plugin-ceph-tempest-py3-base
    description: |
      Integration tests that runs with the ceph devstack plugin and py3.

      This job enable the multiattach feature enable from stein on.

    # This job runs with multiattach enable from stable/stein on.
    branches: ^(?!stable/(ocata|pike|queens|rocky)).*$
    vars:
      devstack_localrc:
        ENABLE_VOLUME_MULTIATTACH: true

- job:
    name: devstack-plugin-ceph-tempest-stein-py3
    parent: devstack-plugin-ceph-tempest-py3
    override-checkout: stable/stein

- job:
    name: devstack-plugin-ceph-tempest-rocky-py3
    parent: devstack-plugin-ceph-tempest-py3
    nodeset: openstack-single-node-xenial
    override-checkout: stable/rocky
    vars:
      devstack_localrc:
        ENABLE_VOLUME_MULTIATTACH: false

- job:
    name: devstack-plugin-ceph-tempest-queens-py3
    parent: devstack-plugin-ceph-tempest-py3
    nodeset: openstack-single-node-xenial
    override-checkout: stable/queens
    vars:
      devstack_localrc:
        ENABLE_VOLUME_MULTIATTACH: false

- project-template:
    name: devstack-plugin-ceph-tempest-jobs
    description: |
      Runs devstack-plugin-ceph-tempest jobs.
    check:
      jobs:
        - devstack-plugin-ceph-tempest-py3:
            irrelevant-files:
              - ^.*\.rst$
              - ^doc/.*$

- project:
    templates:
      - devstack-plugin-ceph-tempest-jobs
    check:
      jobs:
        - openstack-tox-bashate
        - manila-tempest-minimal-dsvm-cephfs-native:
            voting: false
        - manila-tempest-minimal-dsvm-cephfs-nfs:
            voting: false
    gate:
      jobs:
        - openstack-tox-bashate
    experimental:
      jobs:
        - manila-tempest-minimal-dsvm-cephfs-native-centos-7:
            voting: false
        - manila-tempest-minimal-dsvm-cephfs-nfs-centos-7:
            voting: false
        - devstack-plugin-ceph-tempest-stein-py3
        - devstack-plugin-ceph-tempest-rocky-py3
        - devstack-plugin-ceph-tempest-queens-py3
